### ISSUE TITLE
screen issues in volumio v2

### ISSUE THREAD

**Issue by CoolTechProjects** [dhrone/pydPiper#101]
Hi, 
I've done exact installation of pydPiper as in instruction, I'm using it on volumio v2,
I have 2 issues:
1) 'R' letter at the end of first line, on all stream radio stations,
2) problem with clock (while STOP). Please check screenshot.
![IMG_20200618_124048](https://user-images.githubusercontent.com/67101428/85010993-3c4f5e80-b161-11ea-91f4-1920653aa275.jpg)

**Comment by dhrone** [comment]
This looks like you are using a pageFile meant for a different display.  Can you let me know what pageFile you are using and the type of display you have?  It looks like it might be a Winstar WEH...

**Comment by dhrone** [comment]
Closing due to lack of response
