### ISSUE TITLE
ssd 1306 display problem

### ISSUE THREAD

**Issue by yammh** [dhrone/pydPiper#107]
Hi dhrone,

I installed pydpiper in volumio and configured ssd1306, but the display does not work.
The process seems to  work normally. Please check the settings below and let me know if there is any further work to be done.

---------------------------------------------------------------------------------------------------
pydpiper.service settings

ExecStart=/usr/bin/docker run --network=host --privileged -v /var/log:/var/log:rw  dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver ssd1306_i2c  --width 128 --height 64 --i2caddress 0x27 --timezone 'Asia/Seoul' --temperature celcius --pages pages_ssd1306.py
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
volumio@volumio4:~/pydPiper-0.3-alpha$ ps -ef |grep pyd
root       831     2  0 05:24 ?        00:00:00 [kcopyd]
root     32462     1  3 07:31 ?        00:00:00 /usr/bin/docker run --network=host --privileged -v /var/log:/var/log:rw dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver ssd1306_i2c --width 128 --height 64 --i2caddress 0x27 --timezone Asia/Seoul --temperature celcius --pages pages_ssd1306.py
volumio  32565  2855  0 07:31 pts/0    00:00:00 grep pyd
---------------------------------------------------------------------------------------------------
volumio@volumio4:~/pydPiper-0.3-alpha$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
volumio@volumio4:~/pydPiper-0.3-alpha$ ll /dev/i2c*
crw-rw---- 1 root i2c 89, 1 Sep 16 05:24 /dev/i2c-1
volumio@volumio4:~/pydPiper-0.3-alpha$

![raspi](https://user-images.githubusercontent.com/71372376/93307002-823cc100-f83b-11ea-82f8-16def76aa3a4.jpg)

**Comment by dhrone** [comment]
Your I2C address seems to be incorrect according to your i2cdetect results.  That showed a single device on the i2c bus with an address of 0x3C.  You might try that address instead of 0x27.

If that doesn't work though, it would be good to verify that the display is wired correctly before trying to work with pydPiper.  Take a look at the [Luma.Oled Documentation](https://luma-oled.readthedocs.io/en/latest/intro.html).  Pay particular attention to the Hardware and Installation pages.  If you can get one of the simple example programs to work, it will be easier to get pydPiper working for you.

**Comment by yammh** [comment]
> Your I2C address seems to be incorrect according to your i2cdetect results. That showed a single device on the i2c bus with an address of 0x3C. You might try that address instead of 0x27.
> 
> If that doesn't work though, it would be good to verify that the display is wired correctly before trying to work with pydPiper. Take a look at the [Luma.Oled Documentation](https://luma-oled.readthedocs.io/en/latest/intro.html). Pay particular attention to the Hardware and Installation pages. If you can get one of the simple example programs to work, it will be easier to get pydPiper working for you.

Hi dhrone,

i changed address to 0x3c. And then, The display works well.
Thank you for your help.
