### ISSUE TITLE
Oled SSD1311 i2c

### ISSUE THREAD

**Issue by livs2021** [dhrone/pydPiper#118]
I just buy an oled (https://www.ebay.com/itm/IIC-I2C-2002-20x02-OLED-Module-Display-For-Arduino-PIC-AVR-ARM-/131059330863) and try to start pydpiper with no success, driver hd44780_i2c.
I test the sample code indicated by seller and it works (The code here https://github.com/jafrado/2004_i2c_oled)
My understanding is the problem is initialization as ssd1311 is not full compatible with hd44780.
Any help to point what to change?
I have no skills for programming.
Thanks.

**Comment by dhrone** [comment]
Unfortunately, pydPiper does not support the SSD1311 controller.  It may be possible that it gets added to a future version though.  All of the code for running the displays that pydPiper used has been updated and moved to the luma.oled and luma.lcd projects.  If pydPiper ever supports this display, it will happen there first.
