### ISSUE TITLE
3 boxes right hand side on bottom row.

### ISSUE THREAD

**Issue by pkarza** [dhrone/pydPiper#122]
Well - after pulling my hair out a bit, I got this working...but the clock has no issues with the display, but the web radio gives three boxes on the second line.. is this normal?
![IMG_20210321_174525](https://user-images.githubusercontent.com/3519819/111925240-9cb35980-8a6d-11eb-9053-2f1e46a119e5.jpg)

**Comment by dhrone** [comment]
Yes, it is expected.  That is the `songprogress` bar that shows how much of a song has been played.  When playing streams though it quickly fills up if the streaming source does not change the `elapsed` value.  If you want to get rid of that then you should remove `, ('songprogress',65,8)` from the `playartist_radio`, `playalbum_radio`, and `playtitle_radio` entries within the `CANVAS` section of your pageFile (presumably `pages_lcd_16x2.py`).

**Comment by pkarza** [comment]
thanks!

**Comment by dhrone** [comment]
I think this issue is closed.  Feel free to reopen if you disagree.
