### ISSUE TITLE
How to center icons on large screens

### ISSUE THREAD

**Issue by remy1961** [dhrone/pydPiper#37]
![play2](https://user-images.githubusercontent.com/42610118/45596785-966d2f80-b98f-11e8-80a0-db7b2e049393.jpg)
Hi dhrone. I am editing my page file for ssd1306 to incorporate icons (play, stop, repeat, shuffle). Is it possible to have this play icon right at the center of the screen? (128x64 oled). I have set the right size and justification center but it is still at the top of the screen. Any idea?
Remy

**Comment by dhrone** [comment]
There is currently no vertical justification implemented.  You can move the widgets lower in the Y dimension within the CANVASES section.

```
CANVASES = {
    # ...
    'showplay_canvas': { 'widgets': [ ('showplay',0,8) ], 'size':(100,32) }
}
```

**Comment by remy1961** [comment]
Thank you. Will try that this week end.

**Comment by remy1961** [comment]
It worked. Creating a canvas did the trick. Thank you very much.
Remy
