### ISSUE TITLE
my LCD definition not found

### ISSUE THREAD

**Issue by bibmuseli** [dhrone/pydPiper#47]

**Comment by bibmuseli** [comment]
I copied the existing script to a new file called bando_lcd.py

volumio@volumio:/pydPiper-0.3-alpha$ ls -alt
total 244
drwxrwxr-x 6 root root  4096 Dec  7 13:16 .
-rwxr-xr-x 1 root root  8390 Dec  7 13:16 bando_lcd.py
-rwxrwxr-x 1 root root  8390 Dec  7 12:57 pages_lcd_20x4.py

I then edited the service file.

volumio@volumio:/etc/systemd/system$ pg pydpiper.service to point to the new pages file.

# HD44780 LCD 20x4 display with I2C interface on address 0x27
ExecStart=/usr/bin/docker run --network=host --privileged -v /var/log:/var/log:rw  dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver hd44780_i2c  --width 100 --height 32 --i2caddress 0x3f --timezone 'Europe/London' --temperature fahrenheit --pages bando_lcd.py

I restarted Volumio and got the following error.

volumio@volumio:/var/log$ pg pydPiper.log
2018-12-07 13:23:17,643:INFO:pydPiper starting
2018-12-07 13:23:20,369:CRITICAL:Page file bando_lcd.py was unable to be loaded
2018-12-07 13:23:20,372:ERROR:Uncaught exception
Traceback (most recent call last):
  File "/app/pydPiper.py", line 629, in <module>
    dc.load(pagefile, mc.musicdata,mc.musicdata_prev )
  File "/app/displays/display.py", line 1294, in load
    newpages = imp.load_source('pages', file)
IOError: [Errno 2] No such file or directory
2018-12-07 13:23:20,465:ERROR:Player status at exception

what did i do wrong?

**Comment by MikkelLau** [comment]
Try looking at the comment from this issue from the 25th of may: https://github.com/dhrone/pydPiper/issues/29
Follow the instructions and you will get an more automated way where your apply your display data, i2c bus address and so on...
The you don't have to create the ExecStart file..

**Comment by dhrone** [comment]
One of these days I'm going to drop out of docker again.  Its caused as many problems as it fixed...

Unless you explicitly grant the docker container permission to access your local disk, it doesn't have access to it.  So the copy of bando_lcd.py that you've created exists outside of the docker container and the code running in the container can't see it.  Try...

`ExecStart=/usr/bin/docker run --network=host --privileged -v /var/log:/var/log:rw -v /home/volumio/pydPiper:/app:rw dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver hd44780_i2c --width 100 --height 32 --i2caddress 0x3f --timezone 'Europe/London' --temperature fahrenheit --pages bando_lcd.py`

Note the addition of 

`-v /home/volumio/pydPiper:/app:rw`

This replaces the contents of the containers /app directory with the contents of /home/volumio/pydPiper allowing the container to see the changes you've made.

**Comment by dhrone** [comment]
I'm assuming this is resolved.  Closing for now.  Please re-open if you are still having problems.
