### ISSUE TITLE
Use both volumio as lms as source

### ISSUE THREAD

**Issue by cortegedusage** [dhrone/pydPiper#48]
Would it be possible to use both lms and volumio as a source for the display?

I love the sound of volumio, 
but I do love the multiroom system of lms...

any thoughts on this?

thanks
Dennis

**Comment by dhrone** [comment]
It is not currently supported but it is technically possible.  I used to support running multiple meta-data sources but stopped several versions back.  It probably more of a testing issue than anything else but I do not have time to work on it at the moment.

**Comment by cortegedusage** [comment]
ok.
no problem.
I can live with it as it is.

thanks for the reply!

cheers
Dennis
