### ISSUE TITLE
Big clock edit and customize

### ISSUE THREAD

**Issue by elpaul** [dhrone/pydPiper#55]
Hello everybody.
dhrone - good job!
I changed the time zone and clock format for 24 hours. It works perfectly on Volumio 2.555 and HD44780i2c 20x4 display.
What do I have to do to remove "AM/PM" text behind the clock?
BR

**Comment by dhrone** [comment]
Remove the ampm widget from the stoptime and stoptimeweather canvases.

So change...
`
     'stoptime':        { 'widgets': [ ('time',10,8), ('ampm',75,8) ], 'size':(100,32) },
     'stoptimeweather': { 'widgets': [ ('time',0,0), ('ampm',65,0), ('temphilow',75,0), ('conditions2',0,24), ('temp',75,24) ], 'size':(100,32) },
`

to...
`
     'stoptime':        { 'widgets': [ ('time',10,8) ], 'size':(100,32) },
     'stoptimeweather': { 'widgets': [ ('time',0,0), ('temphilow',75,0), ('conditions2',0,24), ('temp',75,24) ], 'size':(100,32) },
`

**Comment by elpaul** [comment]
Thank You so much!

![24h](https://user-images.githubusercontent.com/9497662/54869312-edb4e800-4d96-11e9-9ec3-82cc1466185a.jpg)
Solved.

**Comment by dhrone** [comment]
Glad to help.  What display are you using?  It looks interesting.  Could you recommend a part # and supplier?

**Comment by elpaul** [comment]
Winstar WEH002004BL I bought in Poland at a local store for the equivalent 25 $.
At the beginning I wanted to run it on the winstar_weg driver, but the display did not work at all.
 But working good with i2c converter + HD44780i2c driver.
One problem is initialization after soft reboot. I have to turn off power each time.
In the manual I found information that I should send 5 times 0x00 with delay of 100us and omit the busy flag, but I do not know how to do it. (I'm not a programmer.)

**Comment by dhrone** [comment]
It's interesting that the winstar_weg driver did not work for you.  I just double checked that which driver chipset the WEH002004BL uses and it is identical to the WEH001602 (WS0010).  The winstar_weg driver has more features than the HD44780 especially with custom characters.  Which i2c converter are you using?

**Comment by elpaul** [comment]
Exactly, exactly. I bought it for it. It puzzles me too. I spent two weekends over this oled, but without success.  WEH2004 has two WS0010 controllers, maybe this is the reason?
In the end I took the i2c converter from the old LCD, soldered and ... the display runed right away,( but as 44780).
The converter is on PCF8574 [link](https://allegro.pl/oferta/konwerter-lcd-hd44780-i2c-iic-twi-arduino-avr-arm-5900520984?snapshot=MjAxOS0wMy0xNlQxNDowNzoyOS42NDNaO2J1eWVyOzgwZGM0ZDc4MWQ3M2NiYzE5YTYzZmNiMzI3ZjlkM2QzZjljNGVlMzQ0NThiNGI1OGU1MDNkZmIzNDEzNzUyMTc%3D)

**Comment by elpaul** [comment]
Which software do you use to edit the font bitmap file?

**Comment by Prfacia** [comment]
Hi,
how can I change the time zone and clock format for 24 hours?

**Comment by hcanning87** [comment]
Hi @elpaul , I know this thread is ancient, sorry! I am having exactly the same problem as you did where the OLED display works perfectly until you soft reboot or restart the pydPiper service - a hard power off/on is required to get it to initialise properly.  I have tried getting it to send 0x00 5 times in the hd44780 driver file but this just results in a blank display.  Did you ever get to the bottom of it?
