### ISSUE TITLE
issue and possible solution with installation on Runeaudio

### ISSUE THREAD

**Issue by bheuts** [dhrone/pydPiper#56]
First I want to thank you for writing this excelent program and sharing it. It is very much appreciated.
Lately after installing your software I ran into a problem and solved it. Now I want to share my experience and hope that it might be of use for someone.

I installed PydPiper on a fresh installation of Runeaudio by executing:

_git clone https://github.com/dhrone/pydPiper
cd pydPiper
chmod 755 rune_version5.0_install.sh
./rune_version5.0_install.sh_

After finishing the configuration function, there was no output on the screen.
I stopped the service and executed in a terminal:

_/root/.local/bin/pipenv run python2 pydPiper.py_

The script stopped with the following error:

_ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "pydPiper.py", line 716, in <module>
    lcd = displays.hd44780_i2c.hd44780_i2c(rows, cols, i2c_address, i2c_port, enable)
  File "/root/pydPiper/displays/hd44780_i2c.py", line 114, in __init__
    self.bus = smbus.SMBus(i2c_bus)
NameError: global name 'smbus' is not defined
Uncaught exception
Traceback (most recent call last):
  File "pydPiper.py", line 716, in <module>
    lcd = displays.hd44780_i2c.hd44780_i2c(rows, cols, i2c_address, i2c_port, enable)
  File "/root/pydPiper/displays/hd44780_i2c.py", line 114, in __init__
    self.bus = smbus.SMBus(i2c_bus)
NameError: global name 'smbus' is not defined
Traceback (most recent call last):
  File "pydPiper.py", line 716, in <module>
    lcd = displays.hd44780_i2c.hd44780_i2c(rows, cols, i2c_address, i2c_port, enable)
  File "/root/pydPiper/displays/hd44780_i2c.py", line 114, in __init__
    self.bus = smbus.SMBus(i2c_bus)
NameError: global name 'smbus' is not defined_

I thought that maybe the smbus module is missing.
I then executed:

_~/.local/bin/pipenv install smbus_

Now everything works as expected.

I think it would be better to change line 13 in rune_version5.0_install.sh
from:
~/.local/bin/pipenv install moment python-mpd2 pyLMS redis pyOWM luma.oled socketIO-client Pillow
into:
~/.local/bin/pipenv install moment python-mpd2 pyLMS redis pyOWM luma.oled socketIO-client Pillow smbus

Kind regards,

Bart

**Comment by dhrone** [comment]
Change added and thanks for the debug.
