### ISSUE TITLE
strange characters after installation

### ISSUE THREAD

**Issue by slawek125** [dhrone/pydPiper#59]
I have the following problem, after installing the plugin the display shows strange characters. These characters are movable. It looks like the plug works only strange characters are shown.
display is hd44780 connection via gpio. Volumio 2 system.
thank you for your help because I do not know what to do about it anymore.

Link to photo of screen:

https://drive.google.com/file/d/106ub3Dm5ACxu8BrvsuU89A_60QgPEYU_/view?usp=drivesdk

**Comment by dhrone** [comment]
Quick questions needed to respond intelligently...

How is the display wired to the Pi?  Are you sure you have the pin settings correct?
Which Pi are you using?
What version of Volumio?
Have you gotten any other programs to run successfully?  If so, which programs?  

If you haven't, try instructions from  (e.g. https://cdn-learn.adafruit.com/downloads/pdf/drive-a-16x2-lcd-directly-with-a-raspberry-pi.pdf).

**Comment by slawek125** [comment]
Hello thanks for Your reply.
Display is wired like in your link.
checked pin wiring and its correct.
Volumio version latest.
Raspberry pi3 b V1.2

In old version of Volumio LCD works with plugin from Saiyato.

**Comment by slawek125** [comment]
the problem was solved, after replacing the second power supply, the display functions properly.
The problem is in the power supply.

**Comment by dhrone** [comment]
Glad to hear that you solved your problem.
