### ISSUE TITLE
Rune install fails since 13/9, unable to install pillow

### ISSUE THREAD

**Issue by Alien8ions** [dhrone/pydPiper#68]
Hi

I've had the need to reinstall rune 0.5, and I'm testing the new Re 1.1 version as well.
Since yesterday the install script fails because PIL module can't load.
There are timeout errors at the end of the install script.

 ~/.local/bin/pipenv run python2 pydPiper.py            
Traceback (most recent call last):                                                   
  File "pydPiper.py", line 10, in <module>                                           
    import displays                                                                  
  File "/root/pydPiper/displays/__init__.py", line 4, in <module>                    
    import display                                                                   
  File "/root/pydPiper/displays/display.py", line 11, in <module>                    
    from PIL import Image                                                            
ImportError: No module named PIL

Is it possible to install manually?

Diego

**Comment by dhrone** [comment]
Yes, that should work.

I'm wondering though if the problem might relate to the virtual environment that pipenv maintains.  Did the install script through an error when it was attempting to install Pillow?

**Comment by Alien8ions** [comment]
Yes, it fails  with error. Url not found, timeout while downloading.

Couldn't catch it, but its a long block of errors.

Meanwhile I've managed to use volumio dockerized install and adjusting for rune.
It now runs again.

Don't know if it is useful but docker can be installed using pacman manager. At first that failed as well because of version error on containerd dependency. So installed that one seperately to get it to work.

I didn't try  to install pillow using pip.

Irony is that I now have a music making clock, because of reinstall on new Rune Re1 version it seems the status updates through redis are broken, so needed fresh install for debug
D

**Comment by Alien8ions** [comment]
pacman -S docker works fine with adapted .service file
Script runs fine now...

Issue solved
