### ISSUE TITLE
Changing SPOP to Spotify

### ISSUE THREAD

**Issue by slawek125** [dhrone/pydPiper#83]
Hello,

When playing Spotify 'actPlayer' shows SPOP.
How can I change SPOP to Spotify ?

Thank You.

**Comment by dhrone** [comment]
What music source are you using?

**Comment by slawek125** [comment]
Spotify Plugin playing Spotify from volumio.

**Comment by dhrone** [comment]
Ok.  This is actual a bug in musicdata_spop.py and I've made the change in the source code (line 155).  You can either edit your local copy or pull it down from the repo.

**Comment by slawek125** [comment]
Thank You dhrone,

Now displaying OK, problem solved.
