### ISSUE TITLE
genre not a valid variable

### ISSUE THREAD

**Issue by NicoOosterwijk** [dhrone/pydPiper#87]
Superb piece of program, I love it and use it every day to display song info on my 16x2 LCD display. However, I'm missing the music's genre.

Is it possible to add the music's genre as a variable so it an be used on the display?

tia,

.Nico

**Comment by dhrone** [comment]
Currently no.  pydPiper is only set up to make the underlying distributions metadata available.  As far as I know none of the popular distributions (e.g. Volumio, Rune) provide genre data.  It would theoretically be possible to add a lookup function that pulled genre data from somewhere else but the system does not currently implement that functionality.

**Comment by NicoOosterwijk** [comment]
Ok, I get it. Thanks for your prompt answer, please close this issue.

Rgds,

Nico

Op 15 feb. 2020 om 14:07 heeft dhrone <notifications@github.com> het volgende geschreven:

﻿

Currently no. pydPiper is only set up to make the underlying distributions metadata available. As far as I know none of the popular distributions (e.g. Volumio, Rune) provide genre data. It would theoretically be possible to add a lookup function that pulled genre data from somewhere else but the system does not currently implement that functionality.
